server:
  port: 8080

# user local PostgreSQL, the Docker version is now working yet
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-data-pet
    username: postgres
    password: admin
    initializtaion-mode: always
#    initialize: true
#    schema: classpath:/schema-postgres.sql
#    continue-on-error: true
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: none
#      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_schema: schema
