server:
  port: 8080

# user local PostgreSQL, the Docker version is now working yet
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-data-pet
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
