server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-data-pet
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
