server:
  port: 8080

# user local PostgreSQL, the Docker version is not working yet
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-data-pet
    username: postgres
    password: admin
    initialization-mode: always
    schema: classpath:/schema.sql
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
